# config

# interval in mins
interval: 5

bbdc:
  username: "FIN4DATE"
  password: "PASSWORD"

chromedriver:
#  host:  http://localhost:4444
  host:  http://chrome-selenium:4444


telegram:
  enabled: True
  token: "6013552545:AAHq************"
  chat_id: "-100*********"
