# config

health_report_timing: 30

bbdc:
  username: "FIN4DATE"
  password: "PASSWORD"
  practical_lesson_target: "3.01" # check if you have the correct lesson target, and it's described in lesson_map.py
  theory_lesson_target: "PPL2"
  test_target: "RTT"

chromedriver:
#  host:  http://localhost:4444
  host:  http://chrome-selenium:4444


telegram:
  enabled: True
  token: "6013552545:AAHq************"
  chat_id: "-100*********"
