version: '3.0'

volumes:
  vl-postgres:

services:
  app:
    build:
        context: .
        dockerfile: Dockerfile

# docker run --rm -p 4444:4444 --shm-size="2g" -e SE_NODE_GRID_URL=http://localhost:4444 --name selenium selenium/standalone-chrome:4.8.0-20230202
  chrome-selenium:
    image: selenium/standalone-chrome:4.8.0-20230202
    ports:
      - "4444:4444"
    environment:
       - SE_NODE_GRID_URL=http://localhost:4444
       - SE_NODE_MAX_SESSIONS=2