from datetime import datetime
import json
from unittest import TestCase

from app import BBDCProcessor
from config import load_config
from model import Slot


class TestBBDCProcessor(TestCase):
    def test__find_available_slots(self):
        config_path = "config.yaml"
        config = load_config(config_path)
        bbdc = BBDCProcessor(config)
        resp = json.loads(mock_practical_output)
        slots = bbdc._find_available_slots_in_api_response(resp)
        self.assertEqual(len(slots), 2)
        assert_slots = [
            Slot(1156639,
                 "SESSION 3",
                 datetime.strptime("2023-03-30 11:30:00", '%Y-%m-%d %H:%M:%S'),
                 datetime.strptime("2023-03-30 13:10:00", '%Y-%m-%d %H:%M:%S')),
            Slot(1156545,
                 "SESSION 6",
                 datetime.strptime("2023-03-28 17:10:00", '%Y-%m-%d %H:%M:%S'),
                 datetime.strptime("2023-03-28 18:50:00", '%Y-%m-%d %H:%M:%S'),
                 )
        ]
        self.assertEqual(slots[0], assert_slots[0])
        self.assertEqual(slots[1], assert_slots[1])

    def test__find_empty_slots_theory(self):
        config_path = "config.yaml"
        config = load_config(config_path)
        bbdc = BBDCProcessor(config)
        resp = json.loads(mock_empty_theory)
        slots = bbdc._find_available_slots_in_api_response(resp)
        self.assertEqual(len(slots), 0)

    def test__find_available_theory_slots(self):
        config_path = "config.yaml"
        config = load_config(config_path)
        bbdc = BBDCProcessor(config)
        resp = json.loads(mock_theory_output)
        slots = bbdc._find_available_slots_in_api_response(resp)
        self.assertEqual(len(slots), 4)
        assert_slots = [
            Slot(4944954,
                 "SESSION 8",
                 datetime.strptime("2023-04-12 00:00:00", '%Y-%m-%d %H:%M:%S'),
                 datetime.strptime("21:10", '%H:%M').time(),
                 datetime.strptime("22:50", '%H:%M').time())
        ]
        self.assertEqual(slots[0], assert_slots[0])


mock_practical_output = """{
    "success": true,
    "message": null,
    "code": 0,
    "routeToURL": null,
    "data": {
        "releasedSlotMonthList": [
            {
                "slotMonthEn": "Mar'23",
                "slotMonthYm": "202303"
            },
            {
                "slotMonthEn": "Apr'23",
                "slotMonthYm": "202304"
            },
            {
                "slotMonthEn": "May'23",
                "slotMonthYm": "202305"
            }
        ],
        "releasedSlotListGroupByDay": {
            "2023-03-30 00:00:00": [
                {
                    "slotId": 1156639,
                    "slotIdEnc": "7lixj9K/RRtbwyy/mgBraA==",
                    "slotRefName": "SESSION 3",
                    "slotRefDate": "2023-03-30 00:00:00",
                    "startTime": "11:30",
                    "endTime": "13:10",
                    "trainingFee": 24,
                    "gst": 8,
                    "gstFee": 1.92,
                    "baseFee": 25.92,
                    "totalFee": 25.92,
                    "warmUpWithGstFee": null,
                    "rentalWithGstFee": null,
                    "commWithGstFee": null,
                    "fixedInstructorSurcharge": null,
                    "venueId": null,
                    "slotAvlComputed": false,
                    "bookingProgress": "Available",
                    "bookingProgressEnc": "Y87cWM3Riv07CkGdc76ZE94t8GcHuXacZBnv+DAt6vQ=",
                    "computedSlotAvl": 0,
                    "success": false,
                    "message": null,
                    "startDateTime": null,
                    "c2psrSlotId": 1156639,
                    "c2psrCourseType": "2B",
                    "c2psrTrainingDate": "2023-03-29T16:00:00.000+00:00",
                    "c2psrSessionNo": 3,
                    "c2psrStartTime": null,
                    "c2psrEndTime": null,
                    "c2psrStageSubNo": "RC",
                    "c2psrBikeModel": "CB125",
                    "c2psrPriceType": "CD",
                    "c2psrSlotAssign": 9,
                    "c2psrSlotAvl": 1,
                    "c2psrTrysell": 0,
                    "c2psrCutOffDate": "2023-03-29T16:00:00.000+00:00",
                    "c2psrTakeBack": 0,
                    "c2psrUserId": "1010",
                    "c2psrTimeStamp": "2023-03-01 15:37:22.0",
                    "c2psrVenueId": 1,
                    "venueName": "BBDC",
                    "c2PracTrainingFeeDtlDTO": {
                        "c2pId": 101,
                        "c2pClassType": "2B",
                        "c2pType": "Circuit",
                        "c2pDayTrainingFee": 24,
                        "c2pNightTrainingFee": 28,
                        "c2pDayGst": 8,
                        "c2pNightGst": 8,
                        "c2pDateOpt": "Booking Date",
                        "c2pEffectiveDate": "2022-12-31T16:00:00.000+00:00",
                        "c2pUserId": "1152",
                        "c2pTimeStamp": "2022-12-22T02:42:24.000+00:00"
                    }
                },
                {
                    "slotId": 1156669,
                    "slotIdEnc": "qXW0A2wNGG2swQYQAMexiw==",
                    "slotRefName": "SESSION 4",
                    "slotRefDate": "2023-03-30 00:00:00",
                    "startTime": "13:20",
                    "endTime": "15:00",
                    "trainingFee": 24,
                    "gst": 8,
                    "gstFee": 1.92,
                    "baseFee": 25.92,
                    "totalFee": 25.92,
                    "warmUpWithGstFee": null,
                    "rentalWithGstFee": null,
                    "commWithGstFee": null,
                    "fixedInstructorSurcharge": null,
                    "venueId": null,
                    "slotAvlComputed": false,
                    "bookingProgress": "Sold Out",
                    "bookingProgressEnc": "uHwIQJlxJEAzwIgyK80YLkUB1Y+GrMnookJ87dGEFKo=",
                    "computedSlotAvl": 0,
                    "success": false,
                    "message": null,
                    "startDateTime": null,
                    "c2psrSlotId": 1156669,
                    "c2psrCourseType": "2B",
                    "c2psrTrainingDate": "2023-03-29T16:00:00.000+00:00",
                    "c2psrSessionNo": 4,
                    "c2psrStartTime": null,
                    "c2psrEndTime": null,
                    "c2psrStageSubNo": "RC",
                    "c2psrBikeModel": "CB125",
                    "c2psrPriceType": "CD",
                    "c2psrSlotAssign": 9,
                    "c2psrSlotAvl": 0,
                    "c2psrTrysell": 0,
                    "c2psrCutOffDate": "2023-03-29T16:00:00.000+00:00",
                    "c2psrTakeBack": 0,
                    "c2psrUserId": "1010",
                    "c2psrTimeStamp": "2023-03-13 14:35:48.0",
                    "c2psrVenueId": 1,
                    "venueName": "BBDC",
                    "c2PracTrainingFeeDtlDTO": {
                        "c2pId": 101,
                        "c2pClassType": "2B",
                        "c2pType": "Circuit",
                        "c2pDayTrainingFee": 24,
                        "c2pNightTrainingFee": 28,
                        "c2pDayGst": 8,
                        "c2pNightGst": 8,
                        "c2pDateOpt": "Booking Date",
                        "c2pEffectiveDate": "2022-12-31T16:00:00.000+00:00",
                        "c2pUserId": "1152",
                        "c2pTimeStamp": "2022-12-22T02:42:24.000+00:00"
                    }
                },
                {
                    "slotId": 1156701,
                    "slotIdEnc": "x9GcP63GjDNR69UMOy2Ipg==",
                    "slotRefName": "SESSION 5",
                    "slotRefDate": "2023-03-30 00:00:00",
                    "startTime": "15:20",
                    "endTime": "17:00",
                    "trainingFee": 24,
                    "gst": 8,
                    "gstFee": 1.92,
                    "baseFee": 25.92,
                    "totalFee": 25.92,
                    "warmUpWithGstFee": null,
                    "rentalWithGstFee": null,
                    "commWithGstFee": null,
                    "fixedInstructorSurcharge": null,
                    "venueId": null,
                    "slotAvlComputed": false,
                    "bookingProgress": "Sold Out",
                    "bookingProgressEnc": "omQgb9HTwxK7Brw4M44xXR1tgBqLEuiMPF4NihRn1do=",
                    "computedSlotAvl": 0,
                    "success": false,
                    "message": null,
                    "startDateTime": null,
                    "c2psrSlotId": 1156701,
                    "c2psrCourseType": "2B",
                    "c2psrTrainingDate": "2023-03-29T16:00:00.000+00:00",
                    "c2psrSessionNo": 5,
                    "c2psrStartTime": null,
                    "c2psrEndTime": null,
                    "c2psrStageSubNo": "RC",
                    "c2psrBikeModel": "CB125",
                    "c2psrPriceType": "CD",
                    "c2psrSlotAssign": 9,
                    "c2psrSlotAvl": 0,
                    "c2psrTrysell": 0,
                    "c2psrCutOffDate": "2023-03-29T16:00:00.000+00:00",
                    "c2psrTakeBack": 0,
                    "c2psrUserId": "1010",
                    "c2psrTimeStamp": "2023-03-01 15:53:30.0",
                    "c2psrVenueId": 1,
                    "venueName": "BBDC",
                    "c2PracTrainingFeeDtlDTO": {
                        "c2pId": 101,
                        "c2pClassType": "2B",
                        "c2pType": "Circuit",
                        "c2pDayTrainingFee": 24,
                        "c2pNightTrainingFee": 28,
                        "c2pDayGst": 8,
                        "c2pNightGst": 8,
                        "c2pDateOpt": "Booking Date",
                        "c2pEffectiveDate": "2022-12-31T16:00:00.000+00:00",
                        "c2pUserId": "1152",
                        "c2pTimeStamp": "2022-12-22T02:42:24.000+00:00"
                    }
                },
                {
                    "slotId": 1156729,
                    "slotIdEnc": "HIqiJJg03qdGQPW/dzI7WQ==",
                    "slotRefName": "SESSION 6",
                    "slotRefDate": "2023-03-30 00:00:00",
                    "startTime": "17:10",
                    "endTime": "18:50",
                    "trainingFee": 28,
                    "gst": 8,
                    "gstFee": 2.24,
                    "baseFee": 30.24,
                    "totalFee": 30.24,
                    "warmUpWithGstFee": null,
                    "rentalWithGstFee": null,
                    "commWithGstFee": null,
                    "fixedInstructorSurcharge": null,
                    "venueId": null,
                    "slotAvlComputed": false,
                    "bookingProgress": "Sold Out",
                    "bookingProgressEnc": "pL/4Q3dgSZsoTYMvcARDCfzEvnSWzM4elfuNtZlGx9M=",
                    "computedSlotAvl": 0,
                    "success": false,
                    "message": null,
                    "startDateTime": null,
                    "c2psrSlotId": 1156729,
                    "c2psrCourseType": "2B",
                    "c2psrTrainingDate": "2023-03-29T16:00:00.000+00:00",
                    "c2psrSessionNo": 6,
                    "c2psrStartTime": null,
                    "c2psrEndTime": null,
                    "c2psrStageSubNo": "RC",
                    "c2psrBikeModel": "CB125",
                    "c2psrPriceType": "CN",
                    "c2psrSlotAssign": 9,
                    "c2psrSlotAvl": 0,
                    "c2psrTrysell": 0,
                    "c2psrCutOffDate": "2023-03-29T16:00:00.000+00:00",
                    "c2psrTakeBack": 0,
                    "c2psrUserId": "1010",
                    "c2psrTimeStamp": "2023-03-01 15:54:38.0",
                    "c2psrVenueId": 1,
                    "venueName": "BBDC",
                    "c2PracTrainingFeeDtlDTO": {
                        "c2pId": 101,
                        "c2pClassType": "2B",
                        "c2pType": "Circuit",
                        "c2pDayTrainingFee": 24,
                        "c2pNightTrainingFee": 28,
                        "c2pDayGst": 8,
                        "c2pNightGst": 8,
                        "c2pDateOpt": "Booking Date",
                        "c2pEffectiveDate": "2022-12-31T16:00:00.000+00:00",
                        "c2pUserId": "1152",
                        "c2pTimeStamp": "2022-12-22T02:42:24.000+00:00"
                    }
                },
                {
                    "slotId": 1156761,
                    "slotIdEnc": "Ux40pfWRqSWWmqk7IkJlkg==",
                    "slotRefName": "SESSION 7",
                    "slotRefDate": "2023-03-30 00:00:00",
                    "startTime": "19:20",
                    "endTime": "21:00",
                    "trainingFee": 28,
                    "gst": 8,
                    "gstFee": 2.24,
                    "baseFee": 30.24,
                    "totalFee": 30.24,
                    "warmUpWithGstFee": null,
                    "rentalWithGstFee": null,
                    "commWithGstFee": null,
                    "fixedInstructorSurcharge": null,
                    "venueId": null,
                    "slotAvlComputed": false,
                    "bookingProgress": "Sold Out",
                    "bookingProgressEnc": "Sf4A8Ghj+nG9ll51ZR18kMDB9liN6W92Hj6aEj6aJO8=",
                    "computedSlotAvl": 0,
                    "success": false,
                    "message": null,
                    "startDateTime": null,
                    "c2psrSlotId": 1156761,
                    "c2psrCourseType": "2B",
                    "c2psrTrainingDate": "2023-03-29T16:00:00.000+00:00",
                    "c2psrSessionNo": 7,
                    "c2psrStartTime": null,
                    "c2psrEndTime": null,
                    "c2psrStageSubNo": "RC",
                    "c2psrBikeModel": "CB125",
                    "c2psrPriceType": "CN",
                    "c2psrSlotAssign": 10,
                    "c2psrSlotAvl": 0,
                    "c2psrTrysell": 0,
                    "c2psrCutOffDate": "2023-03-29T16:00:00.000+00:00",
                    "c2psrTakeBack": 0,
                    "c2psrUserId": "1010",
                    "c2psrTimeStamp": "2023-03-16 09:50:56.0",
                    "c2psrVenueId": 1,
                    "venueName": "BBDC",
                    "c2PracTrainingFeeDtlDTO": {
                        "c2pId": 101,
                        "c2pClassType": "2B",
                        "c2pType": "Circuit",
                        "c2pDayTrainingFee": 24,
                        "c2pNightTrainingFee": 28,
                        "c2pDayGst": 8,
                        "c2pNightGst": 8,
                        "c2pDateOpt": "Booking Date",
                        "c2pEffectiveDate": "2022-12-31T16:00:00.000+00:00",
                        "c2pUserId": "1152",
                        "c2pTimeStamp": "2022-12-22T02:42:24.000+00:00"
                    }
                },
                {
                    "slotId": 1156795,
                    "slotIdEnc": "+c+3HM0nJRkyV94zuDwOjQ==",
                    "slotRefName": "SESSION 8",
                    "slotRefDate": "2023-03-30 00:00:00",
                    "startTime": "21:10",
                    "endTime": "22:50",
                    "trainingFee": 28,
                    "gst": 8,
                    "gstFee": 2.24,
                    "baseFee": 30.24,
                    "totalFee": 30.24,
                    "warmUpWithGstFee": null,
                    "rentalWithGstFee": null,
                    "commWithGstFee": null,
                    "fixedInstructorSurcharge": null,
                    "venueId": null,
                    "slotAvlComputed": false,
                    "bookingProgress": "Sold Out",
                    "bookingProgressEnc": "BCDi3nVol3dBgrd7fCR00e1bjqVEk29wcNrLudiFSDM=",
                    "computedSlotAvl": 0,
                    "success": false,
                    "message": null,
                    "startDateTime": null,
                    "c2psrSlotId": 1156795,
                    "c2psrCourseType": "2B",
                    "c2psrTrainingDate": "2023-03-29T16:00:00.000+00:00",
                    "c2psrSessionNo": 8,
                    "c2psrStartTime": null,
                    "c2psrEndTime": null,
                    "c2psrStageSubNo": "RC",
                    "c2psrBikeModel": "CB125",
                    "c2psrPriceType": "CN",
                    "c2psrSlotAssign": 10,
                    "c2psrSlotAvl": 0,
                    "c2psrTrysell": 0,
                    "c2psrCutOffDate": "2023-03-29T16:00:00.000+00:00",
                    "c2psrTakeBack": 0,
                    "c2psrUserId": "1010",
                    "c2psrTimeStamp": "2023-03-12 09:41:18.0",
                    "c2psrVenueId": 1,
                    "venueName": "BBDC",
                    "c2PracTrainingFeeDtlDTO": {
                        "c2pId": 101,
                        "c2pClassType": "2B",
                        "c2pType": "Circuit",
                        "c2pDayTrainingFee": 24,
                        "c2pNightTrainingFee": 28,
                        "c2pDayGst": 8,
                        "c2pNightGst": 8,
                        "c2pDateOpt": "Booking Date",
                        "c2pEffectiveDate": "2022-12-31T16:00:00.000+00:00",
                        "c2pUserId": "1152",
                        "c2pTimeStamp": "2022-12-22T02:42:24.000+00:00"
                    }
                }
            ],
            "2023-03-28 00:00:00": [
                {
                    "slotId": 1156455,
                    "slotIdEnc": "87K+QFpyumvMZQYTlFj3CQ==",
                    "slotRefName": "SESSION 3",
                    "slotRefDate": "2023-03-28 00:00:00",
                    "startTime": "11:30",
                    "endTime": "13:10",
                    "trainingFee": 24,
                    "gst": 8,
                    "gstFee": 1.92,
                    "baseFee": 25.92,
                    "totalFee": 25.92,
                    "warmUpWithGstFee": null,
                    "rentalWithGstFee": null,
                    "commWithGstFee": null,
                    "fixedInstructorSurcharge": null,
                    "venueId": null,
                    "slotAvlComputed": false,
                    "bookingProgress": "Sold Out",
                    "bookingProgressEnc": "5Riq/YkXhSWaihhYOb8g+lksV+Lu9nHvGnV4r9aoE9Y=",
                    "computedSlotAvl": 0,
                    "success": false,
                    "message": null,
                    "startDateTime": null,
                    "c2psrSlotId": 1156455,
                    "c2psrCourseType": "2B",
                    "c2psrTrainingDate": "2023-03-27T16:00:00.000+00:00",
                    "c2psrSessionNo": 3,
                    "c2psrStartTime": null,
                    "c2psrEndTime": null,
                    "c2psrStageSubNo": "RC",
                    "c2psrBikeModel": "CB125",
                    "c2psrPriceType": "CD",
                    "c2psrSlotAssign": 9,
                    "c2psrSlotAvl": 0,
                    "c2psrTrysell": 0,
                    "c2psrCutOffDate": "2023-03-27T16:00:00.000+00:00",
                    "c2psrTakeBack": 0,
                    "c2psrUserId": "1010",
                    "c2psrTimeStamp": "2023-02-28 16:12:07.0",
                    "c2psrVenueId": 1,
                    "venueName": "BBDC",
                    "c2PracTrainingFeeDtlDTO": {
                        "c2pId": 101,
                        "c2pClassType": "2B",
                        "c2pType": "Circuit",
                        "c2pDayTrainingFee": 24,
                        "c2pNightTrainingFee": 28,
                        "c2pDayGst": 8,
                        "c2pNightGst": 8,
                        "c2pDateOpt": "Booking Date",
                        "c2pEffectiveDate": "2022-12-31T16:00:00.000+00:00",
                        "c2pUserId": "1152",
                        "c2pTimeStamp": "2022-12-22T02:42:24.000+00:00"
                    }
                },
                {
                    "slotId": 1156485,
                    "slotIdEnc": "9pV7uVcuWKLlwCTRNFKEmw==",
                    "slotRefName": "SESSION 4",
                    "slotRefDate": "2023-03-28 00:00:00",
                    "startTime": "13:20",
                    "endTime": "15:00",
                    "trainingFee": 24,
                    "gst": 8,
                    "gstFee": 1.92,
                    "baseFee": 25.92,
                    "totalFee": 25.92,
                    "warmUpWithGstFee": null,
                    "rentalWithGstFee": null,
                    "commWithGstFee": null,
                    "fixedInstructorSurcharge": null,
                    "venueId": null,
                    "slotAvlComputed": false,
                    "bookingProgress": "Sold Out",
                    "bookingProgressEnc": "bsDBNDus4Jz4nyz4oxOhpuUHX+7auODlqrCzNsuy2yY=",
                    "computedSlotAvl": 0,
                    "success": false,
                    "message": null,
                    "startDateTime": null,
                    "c2psrSlotId": 1156485,
                    "c2psrCourseType": "2B",
                    "c2psrTrainingDate": "2023-03-27T16:00:00.000+00:00",
                    "c2psrSessionNo": 4,
                    "c2psrStartTime": null,
                    "c2psrEndTime": null,
                    "c2psrStageSubNo": "RC",
                    "c2psrBikeModel": "CB125",
                    "c2psrPriceType": "CD",
                    "c2psrSlotAssign": 4,
                    "c2psrSlotAvl": 0,
                    "c2psrTrysell": 0,
                    "c2psrCutOffDate": "2023-03-27T16:00:00.000+00:00",
                    "c2psrTakeBack": 0,
                    "c2psrUserId": "1010",
                    "c2psrTimeStamp": "2023-03-19 10:05:00.0",
                    "c2psrVenueId": 1,
                    "venueName": "BBDC",
                    "c2PracTrainingFeeDtlDTO": {
                        "c2pId": 101,
                        "c2pClassType": "2B",
                        "c2pType": "Circuit",
                        "c2pDayTrainingFee": 24,
                        "c2pNightTrainingFee": 28,
                        "c2pDayGst": 8,
                        "c2pNightGst": 8,
                        "c2pDateOpt": "Booking Date",
                        "c2pEffectiveDate": "2022-12-31T16:00:00.000+00:00",
                        "c2pUserId": "1152",
                        "c2pTimeStamp": "2022-12-22T02:42:24.000+00:00"
                    }
                },
                {
                    "slotId": 1156517,
                    "slotIdEnc": "OOXLpSORxnSFJErxZzi7RA==",
                    "slotRefName": "SESSION 5",
                    "slotRefDate": "2023-03-28 00:00:00",
                    "startTime": "15:20",
                    "endTime": "17:00",
                    "trainingFee": 24,
                    "gst": 8,
                    "gstFee": 1.92,
                    "baseFee": 25.92,
                    "totalFee": 25.92,
                    "warmUpWithGstFee": null,
                    "rentalWithGstFee": null,
                    "commWithGstFee": null,
                    "fixedInstructorSurcharge": null,
                    "venueId": null,
                    "slotAvlComputed": false,
                    "bookingProgress": "Sold Out",
                    "bookingProgressEnc": "o6RnhcAcFC28rOTfOCuLTQGoVWHYvZosxZVYF2AZSIU=",
                    "computedSlotAvl": 0,
                    "success": false,
                    "message": null,
                    "startDateTime": null,
                    "c2psrSlotId": 1156517,
                    "c2psrCourseType": "2B",
                    "c2psrTrainingDate": "2023-03-27T16:00:00.000+00:00",
                    "c2psrSessionNo": 5,
                    "c2psrStartTime": null,
                    "c2psrEndTime": null,
                    "c2psrStageSubNo": "RC",
                    "c2psrBikeModel": "CB125",
                    "c2psrPriceType": "CD",
                    "c2psrSlotAssign": 9,
                    "c2psrSlotAvl": 0,
                    "c2psrTrysell": 0,
                    "c2psrCutOffDate": "2023-03-27T16:00:00.000+00:00",
                    "c2psrTakeBack": 0,
                    "c2psrUserId": "1010",
                    "c2psrTimeStamp": "2023-02-28 16:14:35.0",
                    "c2psrVenueId": 1,
                    "venueName": "BBDC",
                    "c2PracTrainingFeeDtlDTO": {
                        "c2pId": 101,
                        "c2pClassType": "2B",
                        "c2pType": "Circuit",
                        "c2pDayTrainingFee": 24,
                        "c2pNightTrainingFee": 28,
                        "c2pDayGst": 8,
                        "c2pNightGst": 8,
                        "c2pDateOpt": "Booking Date",
                        "c2pEffectiveDate": "2022-12-31T16:00:00.000+00:00",
                        "c2pUserId": "1152",
                        "c2pTimeStamp": "2022-12-22T02:42:24.000+00:00"
                    }
                },
                {
                    "slotId": 1156545,
                    "slotIdEnc": "n58r+JYREoazu/kdAHt93A==",
                    "slotRefName": "SESSION 6",
                    "slotRefDate": "2023-03-28 00:00:00",
                    "startTime": "17:10",
                    "endTime": "18:50",
                    "trainingFee": 28,
                    "gst": 8,
                    "gstFee": 2.24,
                    "baseFee": 30.24,
                    "totalFee": 30.24,
                    "warmUpWithGstFee": null,
                    "rentalWithGstFee": null,
                    "commWithGstFee": null,
                    "fixedInstructorSurcharge": null,
                    "venueId": null,
                    "slotAvlComputed": false,
                    "bookingProgress": "Available",
                    "bookingProgressEnc": "A9s4ZlZAm2jjb2qbtChQbey4cm9wwKwwLthDX+FBu4Q=",
                    "computedSlotAvl": 1,
                    "success": false,
                    "message": null,
                    "startDateTime": null,
                    "c2psrSlotId": 1156545,
                    "c2psrCourseType": "2B",
                    "c2psrTrainingDate": "2023-03-27T16:00:00.000+00:00",
                    "c2psrSessionNo": 6,
                    "c2psrStartTime": null,
                    "c2psrEndTime": null,
                    "c2psrStageSubNo": "RC",
                    "c2psrBikeModel": "CB125",
                    "c2psrPriceType": "CN",
                    "c2psrSlotAssign": 9,
                    "c2psrSlotAvl": 1,
                    "c2psrTrysell": 0,
                    "c2psrCutOffDate": "2023-03-27T16:00:00.000+00:00",
                    "c2psrTakeBack": 0,
                    "c2psrUserId": "1010",
                    "c2psrTimeStamp": "2023-02-28 16:16:07.0",
                    "c2psrVenueId": 1,
                    "venueName": "BBDC",
                    "c2PracTrainingFeeDtlDTO": {
                        "c2pId": 101,
                        "c2pClassType": "2B",
                        "c2pType": "Circuit",
                        "c2pDayTrainingFee": 24,
                        "c2pNightTrainingFee": 28,
                        "c2pDayGst": 8,
                        "c2pNightGst": 8,
                        "c2pDateOpt": "Booking Date",
                        "c2pEffectiveDate": "2022-12-31T16:00:00.000+00:00",
                        "c2pUserId": "1152",
                        "c2pTimeStamp": "2022-12-22T02:42:24.000+00:00"
                    }
                },
                {
                    "slotId": 1156577,
                    "slotIdEnc": "/prz140YcRhr4xYq9b6pBQ==",
                    "slotRefName": "SESSION 7",
                    "slotRefDate": "2023-03-28 00:00:00",
                    "startTime": "19:20",
                    "endTime": "21:00",
                    "trainingFee": 28,
                    "gst": 8,
                    "gstFee": 2.24,
                    "baseFee": 30.24,
                    "totalFee": 30.24,
                    "warmUpWithGstFee": null,
                    "rentalWithGstFee": null,
                    "commWithGstFee": null,
                    "fixedInstructorSurcharge": null,
                    "venueId": null,
                    "slotAvlComputed": false,
                    "bookingProgress": "Sold Out",
                    "bookingProgressEnc": "DiKwR+QAfMcOd7nOHDkcY84DDcZX2/WS9UehwV6SGx4=",
                    "computedSlotAvl": 0,
                    "success": false,
                    "message": null,
                    "startDateTime": null,
                    "c2psrSlotId": 1156577,
                    "c2psrCourseType": "2B",
                    "c2psrTrainingDate": "2023-03-27T16:00:00.000+00:00",
                    "c2psrSessionNo": 7,
                    "c2psrStartTime": null,
                    "c2psrEndTime": null,
                    "c2psrStageSubNo": "RC",
                    "c2psrBikeModel": "CB125",
                    "c2psrPriceType": "CN",
                    "c2psrSlotAssign": 10,
                    "c2psrSlotAvl": 0,
                    "c2psrTrysell": 0,
                    "c2psrCutOffDate": "2023-03-27T16:00:00.000+00:00",
                    "c2psrTakeBack": 0,
                    "c2psrUserId": "1010",
                    "c2psrTimeStamp": "2023-03-17 13:50:29.0",
                    "c2psrVenueId": 1,
                    "venueName": "BBDC",
                    "c2PracTrainingFeeDtlDTO": {
                        "c2pId": 101,
                        "c2pClassType": "2B",
                        "c2pType": "Circuit",
                        "c2pDayTrainingFee": 24,
                        "c2pNightTrainingFee": 28,
                        "c2pDayGst": 8,
                        "c2pNightGst": 8,
                        "c2pDateOpt": "Booking Date",
                        "c2pEffectiveDate": "2022-12-31T16:00:00.000+00:00",
                        "c2pUserId": "1152",
                        "c2pTimeStamp": "2022-12-22T02:42:24.000+00:00"
                    }
                },
                {
                    "slotId": 1156611,
                    "slotIdEnc": "XOCw7VQiwvBVBsmA75y2Hg==",
                    "slotRefName": "SESSION 8",
                    "slotRefDate": "2023-03-28 00:00:00",
                    "startTime": "21:10",
                    "endTime": "22:50",
                    "trainingFee": 28,
                    "gst": 8,
                    "gstFee": 2.24,
                    "baseFee": 30.24,
                    "totalFee": 30.24,
                    "warmUpWithGstFee": null,
                    "rentalWithGstFee": null,
                    "commWithGstFee": null,
                    "fixedInstructorSurcharge": null,
                    "venueId": null,
                    "slotAvlComputed": false,
                    "bookingProgress": "Sold Out",
                    "bookingProgressEnc": "oeTqHlWX5Kji/C1kLNIRnkFPL+HXREh8+5u3OieqymQ=",
                    "computedSlotAvl": 0,
                    "success": false,
                    "message": null,
                    "startDateTime": null,
                    "c2psrSlotId": 1156611,
                    "c2psrCourseType": "2B",
                    "c2psrTrainingDate": "2023-03-27T16:00:00.000+00:00",
                    "c2psrSessionNo": 8,
                    "c2psrStartTime": null,
                    "c2psrEndTime": null,
                    "c2psrStageSubNo": "RC",
                    "c2psrBikeModel": "CB125",
                    "c2psrPriceType": "CN",
                    "c2psrSlotAssign": 0,
                    "c2psrSlotAvl": 0,
                    "c2psrTrysell": 0,
                    "c2psrCutOffDate": "2023-03-27T16:00:00.000+00:00",
                    "c2psrTakeBack": 0,
                    "c2psrUserId": "6196",
                    "c2psrTimeStamp": "2023-01-21 09:55:11.0",
                    "c2psrVenueId": 1,
                    "venueName": "BBDC",
                    "c2PracTrainingFeeDtlDTO": {
                        "c2pId": 101,
                        "c2pClassType": "2B",
                        "c2pType": "Circuit",
                        "c2pDayTrainingFee": 24,
                        "c2pNightTrainingFee": 28,
                        "c2pDayGst": 8,
                        "c2pNightGst": 8,
                        "c2pDateOpt": "Booking Date",
                        "c2pEffectiveDate": "2022-12-31T16:00:00.000+00:00",
                        "c2pUserId": "1152",
                        "c2pTimeStamp": "2022-12-22T02:42:24.000+00:00"
                    }
                }
            ]
        },
        "accountBal": 128.79,
        "couNegActive": "0"
    },
    "resultObject": null
}
"""
mock_empty_theory = """
{
    "success": true,
    "message": null,
    "code": 0,
    "routeToURL": null,
    "data": {
        "releasedSlotMonthList": [
            {
                "slotMonthEn": "Mar'23",
                "slotMonthYm": "202303"
            },
            {
                "slotMonthEn": "Apr'23",
                "slotMonthYm": "202304"
            }
        ],
        "releasedSlotListGroupByDay": {},
        "accountBal": 128.79,
        "couNegActive": "0"
    },
    "resultObject": null
}
"""
mock_theory_output = """
{
    "success": true,
    "message": null,
    "code": 0,
    "routeToURL": null,
    "data": {
        "releasedSlotMonthList": [
            {
                "slotMonthEn": "Mar'23",
                "slotMonthYm": "202303"
            },
            {
                "slotMonthEn": "Apr'23",
                "slotMonthYm": "202304"
            }
        ],
        "releasedSlotListGroupByDay": {
            "2023-04-12 00:00:00": [
                {
                    "slotId": 4944954,
                    "slotIdEnc": "Reqs4jBlky/TkucY5hkzqQ==",
                    "slotRefName": "SESSION 8",
                    "slotRefDate": "2023-04-12 00:00:00",
                    "startTime": "21:10",
                    "endTime": "22:50",
                    "trainingFee": 16,
                    "gst": 8,
                    "gstFee": 1.28,
                    "baseFee": 17.28,
                    "totalFee": 17.28,
                    "warmUpWithGstFee": null,
                    "rentalWithGstFee": null,
                    "commWithGstFee": null,
                    "fixedInstructorSurcharge": null,
                    "venueId": 7,
                    "slotAvlComputed": false,
                    "bookingProgress": "Available",
                    "bookingProgressEnc": "0wfQsS1mP9SWWLKmKHI6VVP/Hr6YwLOCBP3aJ2uu6u0=",
                    "computedSlotAvl": 90,
                    "success": false,
                    "message": null,
                    "startDateTime": null,
                    "courseType": "2B",
                    "theoryType": "PPL",
                    "trainingDate": "2023-04-11T16:00:00.000+00:00",
                    "sessionNo": "8",
                    "takeBack": 0,
                    "slotAvl": 90,
                    "trySell": 0,
                    "schType": null,
                    "priceType": "N",
                    "maxCapSlotAvl": 0,
                    "vehicleType": null,
                    "venueName": "HBTL",
                    "venueTotalFee": 0,
                    "theoryTrainingFeeDtlDTO": {
                        "theId": 1152,
                        "theCourseType": "2B",
                        "theTheoryType": "PPL",
                        "theDayTrainingFee": 16,
                        "theDayGst": 8,
                        "theNightTrainingFee": 16,
                        "theNightGst": 8,
                        "theDateOpt": "Booking Date",
                        "theEffectiveDate": "2022-12-31T16:00:00.000+00:00"
                    },
                    "theoryTestFeeDtlDTO": null,
                    "pracTestFeeDtlDTO": null,
                    "clashedFlag": false,
                    "slotRefDateTime": null
                }
            ],
            "2023-04-26 00:00:00": [
                {
                    "slotId": 4944893,
                    "slotIdEnc": "MkJckl2cSRZZ7a0koS/CRQ==",
                    "slotRefName": "SESSION 7",
                    "slotRefDate": "2023-04-26 00:00:00",
                    "startTime": "19:20",
                    "endTime": "21:00",
                    "trainingFee": 16,
                    "gst": 8,
                    "gstFee": 1.28,
                    "baseFee": 17.28,
                    "totalFee": 17.28,
                    "warmUpWithGstFee": null,
                    "rentalWithGstFee": null,
                    "commWithGstFee": null,
                    "fixedInstructorSurcharge": null,
                    "venueId": 7,
                    "slotAvlComputed": false,
                    "bookingProgress": "Available",
                    "bookingProgressEnc": "707rr+SW03+bHiNao2ivgLoIWZ3iQOLVScdKbs1qJU8=",
                    "computedSlotAvl": 97,
                    "success": false,
                    "message": null,
                    "startDateTime": null,
                    "courseType": "2B",
                    "theoryType": "PPL",
                    "trainingDate": "2023-04-25T16:00:00.000+00:00",
                    "sessionNo": "7",
                    "takeBack": 0,
                    "slotAvl": 97,
                    "trySell": 0,
                    "schType": null,
                    "priceType": "N",
                    "maxCapSlotAvl": 0,
                    "vehicleType": null,
                    "venueName": "HBTL",
                    "venueTotalFee": 0,
                    "theoryTrainingFeeDtlDTO": {
                        "theId": 1152,
                        "theCourseType": "2B",
                        "theTheoryType": "PPL",
                        "theDayTrainingFee": 16,
                        "theDayGst": 8,
                        "theNightTrainingFee": 16,
                        "theNightGst": 8,
                        "theDateOpt": "Booking Date",
                        "theEffectiveDate": "2022-12-31T16:00:00.000+00:00"
                    },
                    "theoryTestFeeDtlDTO": null,
                    "pracTestFeeDtlDTO": null,
                    "clashedFlag": false,
                    "slotRefDateTime": null
                }
            ],
            "2023-04-15 00:00:00": [
                {
                    "slotId": 4944657,
                    "slotIdEnc": "ibuRfdGYoyCGQXUHz4V3lQ==",
                    "slotRefName": "SESSION 4",
                    "slotRefDate": "2023-04-15 00:00:00",
                    "startTime": "13:20",
                    "endTime": "15:00",
                    "trainingFee": 16,
                    "gst": 8,
                    "gstFee": 1.28,
                    "baseFee": 17.28,
                    "totalFee": 17.28,
                    "warmUpWithGstFee": null,
                    "rentalWithGstFee": null,
                    "commWithGstFee": null,
                    "fixedInstructorSurcharge": null,
                    "venueId": 7,
                    "slotAvlComputed": false,
                    "bookingProgress": "Available",
                    "bookingProgressEnc": "U6Y602d3SJFtlmOmyk8JCebvmeT2jfSnTam+3OF2byY=",
                    "computedSlotAvl": 93,
                    "success": false,
                    "message": null,
                    "startDateTime": null,
                    "courseType": "2B",
                    "theoryType": "PPL",
                    "trainingDate": "2023-04-14T16:00:00.000+00:00",
                    "sessionNo": "4",
                    "takeBack": 0,
                    "slotAvl": 93,
                    "trySell": 0,
                    "schType": null,
                    "priceType": "N",
                    "maxCapSlotAvl": 0,
                    "vehicleType": null,
                    "venueName": "HBTL",
                    "venueTotalFee": 0,
                    "theoryTrainingFeeDtlDTO": {
                        "theId": 1152,
                        "theCourseType": "2B",
                        "theTheoryType": "PPL",
                        "theDayTrainingFee": 16,
                        "theDayGst": 8,
                        "theNightTrainingFee": 16,
                        "theNightGst": 8,
                        "theDateOpt": "Booking Date",
                        "theEffectiveDate": "2022-12-31T16:00:00.000+00:00"
                    },
                    "theoryTestFeeDtlDTO": null,
                    "pracTestFeeDtlDTO": null,
                    "clashedFlag": false,
                    "slotRefDateTime": null
                }
            ],
            "2023-04-19 00:00:00": [
                {
                    "slotId": 4944526,
                    "slotIdEnc": "7x/uBY28FhvBpmHvnTsXRg==",
                    "slotRefName": "SESSION 2",
                    "slotRefDate": "2023-04-19 00:00:00",
                    "startTime": "09:20",
                    "endTime": "11:00",
                    "trainingFee": 16,
                    "gst": 8,
                    "gstFee": 1.28,
                    "baseFee": 17.28,
                    "totalFee": 17.28,
                    "warmUpWithGstFee": null,
                    "rentalWithGstFee": null,
                    "commWithGstFee": null,
                    "fixedInstructorSurcharge": null,
                    "venueId": 7,
                    "slotAvlComputed": false,
                    "bookingProgress": "Available",
                    "bookingProgressEnc": "Lg/wdK7Zht7XQZBF14WYzE/+7QQ5m+jWeDWztYJIUZQ=",
                    "computedSlotAvl": 97,
                    "success": false,
                    "message": null,
                    "startDateTime": null,
                    "courseType": "2B",
                    "theoryType": "PPL",
                    "trainingDate": "2023-04-18T16:00:00.000+00:00",
                    "sessionNo": "2",
                    "takeBack": 0,
                    "slotAvl": 97,
                    "trySell": 0,
                    "schType": null,
                    "priceType": "N",
                    "maxCapSlotAvl": 0,
                    "vehicleType": null,
                    "venueName": "HBTL",
                    "venueTotalFee": 0,
                    "theoryTrainingFeeDtlDTO": {
                        "theId": 1152,
                        "theCourseType": "2B",
                        "theTheoryType": "PPL",
                        "theDayTrainingFee": 16,
                        "theDayGst": 8,
                        "theNightTrainingFee": 16,
                        "theNightGst": 8,
                        "theDateOpt": "Booking Date",
                        "theEffectiveDate": "2022-12-31T16:00:00.000+00:00"
                    },
                    "theoryTestFeeDtlDTO": null,
                    "pracTestFeeDtlDTO": null,
                    "clashedFlag": false,
                    "slotRefDateTime": null
                }
            ]
        },
        "accountBal": 128.79,
        "couNegActive": "0"
    },
    "resultObject": null
}
"""
